MODPACK_NAME="Beyond Create"
MINECRAFT_VERSION="1.21.1"
NEOFORGE_VERSION="21.1.217"
MODPACK_VERSION="0.0.1"
SERVER_MEMORY="4G"

MOD_IDS_SERVER=(
    ZdLtebKH # RHINO
    8nuqyxbw # KUBEJS
    G5SDYehn # LITHIUM
    kztxpjAA # APPLE SKIN
    43sRR8f6 # JADE
    Z9s9lM56 # JADE ADDONS
)

MOD_IDS_CLIENT=(
    Pb3OXVqC # SODIUM
    xUpTkg0V # XAEROS WORLD MAP
    puXrtfcK # XAEROS MINIMAP
    t3ruzodq # IRIS
)

MOD_IDS_ALL=("${MOD_IDS_SERVER[@]}" "${MOD_IDS_CLIENT[@]}")
